Prevent fatal error because of generated class contract incompatibility
Applies for php 7.1+
Otherwise generated class throw
```
Fatal error: Declaration of ...TwirpError::getMeta($key): string must be compatible with Twirp\Error::getMeta(string $key): string
```